Imported from mbuffer-20080502.tgz.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1867,7 +1867,7 @@ test -n "$target_alias" &&
 
 
 PACKAGE=mbuffer
-VERSION=20080329
+VERSION=20080502
 
 
 test "$prefix" = NONE && prefix=/usr/local
@@ -1880,7 +1880,7 @@ ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-CFLAGS="${CFLAGS=-O}"
+CFLAGS="${CFLAGS=-g -O}"
 
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
@@ -4923,18 +4923,18 @@ else
 echo "$as_me: WARNING: could not find sendfile support" >&2;}
 fi
 
-if test "${ac_cv_header_sendfile_h+set}" = set; then
-  { echo "$as_me:$LINENO: checking for sendfile.h" >&5
-echo $ECHO_N "checking for sendfile.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_sendfile_h+set}" = set; then
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for sys/sendfile.h" >&5
+echo $ECHO_N "checking for sys/sendfile.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_sendfile_h" >&5
-echo "${ECHO_T}$ac_cv_header_sendfile_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_sys_sendfile_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_sendfile_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking sendfile.h usability" >&5
-echo $ECHO_N "checking sendfile.h usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking sys/sendfile.h usability" >&5
+echo $ECHO_N "checking sys/sendfile.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -4942,7 +4942,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <sendfile.h>
+#include <sys/sendfile.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -4974,15 +4974,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking sendfile.h presence" >&5
-echo $ECHO_N "checking sendfile.h presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking sys/sendfile.h presence" >&5
+echo $ECHO_N "checking sys/sendfile.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <sendfile.h>
+#include <sys/sendfile.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -5015,40 +5015,40 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: sendfile.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: sys/sendfile.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: sys/sendfile.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: sendfile.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: sendfile.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: sendfile.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: sendfile.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: sendfile.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: sendfile.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: sendfile.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: sys/sendfile.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: sys/sendfile.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: sys/sendfile.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: sys/sendfile.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: sys/sendfile.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: sys/sendfile.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: sys/sendfile.h: in the future, the compiler will take precedence" >&2;}
 
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for sendfile.h" >&5
-echo $ECHO_N "checking for sendfile.h... $ECHO_C" >&6; }
-if test "${ac_cv_header_sendfile_h+set}" = set; then
+{ echo "$as_me:$LINENO: checking for sys/sendfile.h" >&5
+echo $ECHO_N "checking for sys/sendfile.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_sys_sendfile_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_sendfile_h=$ac_header_preproc
+  ac_cv_header_sys_sendfile_h=$ac_header_preproc
 fi
-{ echo "$as_me:$LINENO: result: $ac_cv_header_sendfile_h" >&5
-echo "${ECHO_T}$ac_cv_header_sendfile_h" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_sys_sendfile_h" >&5
+echo "${ECHO_T}$ac_cv_header_sys_sendfile_h" >&6; }
 
 fi
-if test $ac_cv_header_sendfile_h = yes; then
+if test $ac_cv_header_sys_sendfile_h = yes; then
 
 cat >>confdefs.h <<\_ACEOF
 #define HAVE_SENDFILE_H 1
